[package]
name = "projector"
version = "0.1.0"
authors = ["Timothy Pidashev <pidashev.tim@gmail.com"]
repository = "https://github.com/fhcmedia/projector"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cacao = "0.3.2"
