name: Projector CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  target-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test

# TODO: Add windows and linux build targets as platform is implemented! 
# TODO: Add lint, benchmark, and possibly docgen steps later!