name: Projector CI

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  target-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: lint
      run: cargo clippy --all-targets --all-features
    - name: Test
      run: cargo test
    - name: Bench
      run: cargo bench
    - name: Build
      run: cargo build

# TODO: Add windows and linux build targets as platform is implemented! 